// Generated by rune manifest from spec/runes/info.in-prog.rune.
// Scaffolded once; fill in the bodies. `sync` preserves this file.

import { InfoDto } from "@/src/info/dto/info.ts";

// host runtime facts
export class Info {
  #runtime = "";
  #pid = 0;
  #app = "server";

  gather(): Info {
    this.#runtime = `Deno ${Deno.version.deno}`;
    this.#pid = Deno.pid;
    return this;
  }
  /**
   * @returns a snapshot of host runtime facts, read by the UI
   */
  toDto(): InfoDto {
    const dto = new InfoDto();
    dto.runtime = this.#runtime;
    dto.pid = this.#pid;
    dto.app = this.#app;
    return dto;
  }
}
