// Generated by rune manifest from spec/runes/info.in-prog.rune.
// Edit the body. Re-running manifest will not overwrite this file.
// Info: host runtime facts

import { Info } from "./mod.ts";

Deno.test("Info.gather", () => {
  // Arrange — const subject = new Info();
  // Act — gather(): info
  // Assert — TODO: assert the info result
});

Deno.test("Info.toDto", () => {
  // Arrange — const subject = new Info();
  // Act — toDto(): InfoDto
  // Assert — TODO: assert the InfoDto result
});
