#!/usr/bin/env -S deno run -A
// Regenerate cli/template-manifest.ts from the app/ template.
//
// The scaffolder must know every template file up-front: when installed from
// JSR there is no remote directory listing, so the file set has to be baked in.
// Run this whenever you add/remove/rename a file under app/:
//   deno task gen:manifest
import { relative } from "jsr:@std/path@1";

const TEMPLATE = new URL("../app/", import.meta.url);
const OUT = new URL("./template-manifest.ts", import.meta.url);

// Artifacts that are regenerated by build/install — never shipped in the template.
const SKIP_DIRS = new Set(["_fresh", "node_modules"]);
const SKIP_FILES = new Set(["deno.lock"]);
const skipFile = (n: string) => SKIP_FILES.has(n) || n.endsWith(".log");

const files: string[] = [];
async function walk(dir: URL) {
  for await (const entry of Deno.readDir(dir)) {
    if (entry.isDirectory && SKIP_DIRS.has(entry.name)) continue;
    if (entry.isFile && skipFile(entry.name)) continue;
    const child = new URL(entry.name + (entry.isDirectory ? "/" : ""), dir);
    if (entry.isDirectory) await walk(child);
    else files.push(relative(TEMPLATE.pathname, child.pathname));
  }
}
await walk(TEMPLATE);
files.sort();

const body = `// AUTO-GENERATED by cli/gen-manifest.ts — do not edit by hand.
// Every file copied into a scaffolded app, relative to the app/ template root.
export const TEMPLATE_FILES: readonly string[] = [
${files.map((f) => `  ${JSON.stringify(f)},`).join("\n")}
];
`;
await Deno.writeTextFile(OUT, body);
console.log(`wrote ${files.length} entries → cli/template-manifest.ts`);
