// AUTO-GENERATED by cli/gen-manifest.ts — do not edit by hand.
// Every file copied into a scaffolded app, relative to the app/ template root.
export const TEMPLATE_FILES: readonly string[] = [
  ".gitignore",
  "README.md",
  "assets/styles.css",
  "backend.ts",
  "client.ts",
  "components/Button.tsx",
  "deno.json",
  "islands/Counter.tsx",
  "islands/Info.tsx",
  "main.ts",
  "routes/_app.tsx",
  "routes/api/[name].tsx",
  "routes/index.tsx",
  "server.worker.ts",
  "shell.ts",
  "static/favicon.ico",
  "static/logo.svg",
  "utils.ts",
  "vite.config.ts",
];
