// Generated by rune manifest from spec/runes/info.in-prog.rune:16.
// Edit the body. Re-running manifest will not overwrite this file.

/** the backend app name */
// rune declares: [TYP:nonempty] app: string
// enforced on DTO fields: @IsNotEmpty()
export type App = string;
