// Generated by rune manifest from spec/runes/info.in-prog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsInt, IsNotEmpty, IsString } from "class-validator";
import { ApiProperty } from "#api-doc";

/**
 * a snapshot of host runtime facts, read by the UI
 * @internal
 */
// rune declares: [DTO] InfoDto: runtime, pid, app
export class InfoDto {
  /** the JS runtime version string (e.g. "Deno 2.8.3") */
  // rune declares: [TYP] runtime: string
  @ApiProperty({ description: "the JS runtime version string (e.g. \"Deno 2.8.3\")" })
  @IsString()
  runtime!: string;

  /** the OS process id of the backend */
  // rune declares: [TYP:int] pid: number
  @ApiProperty({ description: "the OS process id of the backend", type: "integer" })
  @IsInt()
  pid!: number;

  /** the backend app name */
  // rune declares: [TYP:nonempty] app: string
  @ApiProperty({ description: "the backend app name", minLength: 1 })
  @IsString()
  @IsNotEmpty()
  app!: string;
}
