// Generated by rune manifest from spec/runes/info.in-prog.rune:14.
// Edit the body. Re-running manifest will not overwrite this file.

/** the OS process id of the backend */
// rune declares: [TYP:int] pid: number
// enforced on DTO fields: @IsInt()
export type Pid = number;
