// Generated by rune manifest from spec/runes/info.in-prog.rune:12.
// Edit the body. Re-running manifest will not overwrite this file.

/** the JS runtime version string (e.g. "Deno 2.8.3") */
// rune declares: [TYP] runtime: string
export type Runtime = string;
