// Generated by rune manifest from spec/runes/info.in-prog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/rune";
import { InfoDto } from "@/src/info/dto/info.ts";
import { read as infoRead } from "@/src/info/domain/coordinators/info-read/mod.ts";

@EndpointController("http")
export class HttpController {
  /**
   * Delegates to coordinator info.read (matched by input/output signature).
   * @returns InfoDto — a snapshot of host runtime facts, read by the UI
   */
  // from spec/runes/info.in-prog.rune:4
  @Endpoint({ path: "read", output: InfoDto, order: 1 })
  read(): Promise<InfoDto> {
    return infoRead({});
  }
}

export const httpModule = endpointModule("Info", [HttpController]);
