// Generated by rune manifest — DO NOT EDIT (regenerated on every `rune sync`).

// Domain nouns (from [NON]):
//   info: host runtime facts
//
// Type vocabulary (from [TYP]):
//   runtime: string — the JS runtime version string (e.g. "Deno 2.8.3")
//   pid: number — the OS process id of the backend
//   app: string — the backend app name
// Public API surface for module "info".

export { read } from "./domain/coordinators/info-read/mod.ts";

