// Generated by rune manifest from spec/runes/info.in-prog.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Recipe (from [REQ] info.read @ spec/runes/info.in-prog.rune:7):
//   1. [NEW] info
//   2. info.gather(): info
//   3. info.toDto(): InfoDto

import { read } from "./mod.ts";

Deno.test("read — happy path", async () => {
  // TODO: implement happy path test
});

