// Generated by rune manifest from spec/runes/info.in-prog.rune:7.
// Edit the body. Re-running manifest will not overwrite this file.

import { InfoDto } from "@/src/info/dto/info.ts";
import { assert } from "#assert";
import { Info } from "@/src/info/domain/business/info/mod.ts";

/**
 * Coordinator for [REQ] info.read({}): InfoDto.
 * @param input {} — passed through unvalidated (no [TYP] contract).
 * @returns InfoDto — asserted before return.
 */
export async function read(input: {}): Promise<InfoDto> {

  // core — pure business logic, no I/O
  const out = readCore(input);

  return assert(InfoDto, out.result, "info.read output");
}

// Pure business logic for info.read — no I/O. Takes the
// request input; returns the result.
function readCore(_input: {}): { result: InfoDto } {
  // Recipe from [REQ] info.read (run in order):
  //   1. [NEW] info  2. info.gather(): info  3. info.toDto(): InfoDto
  const info = new Info();
  info.gather();
  return { result: info.toDto() };
}
