// Generated by rune sync — DO NOT EDIT.
// Module registry: one entry per rune surface, regenerated on every sync as
// runes are added and removed. bootstrap/mod.ts (dev-owned) wires it to keep.

import { httpModule as infoHttpModule } from "@/src/info/entrypoints/http/mod.ts";

export const modules = [
  infoHttpModule,
];
